apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.cloudflare.secret.name }}
  namespace: {{ .Values.namespace  }}
type: Opaque
data:
  {{ .Values.cloudflare.secret.key }}: {{ .Values.cloudflare.apiToken | b64enc }}
